### ISSUE TITLE
Multiple Weapon Parts.

### ISSUE THREAD

**Issue by reihunter360** [wcqiter/cb-build-simulator#10]
Essentially, a part that has both MAIN/SUB

Its only locked to either MAIN or SUB, but not both.

**Comment by HC307** [comment]
https://github.com/wcqiter/cb-build-simulator/issues/8 ticket already exists xD

**Comment by reihunter360** [comment]
> 
> 
> #8 ticket already exists xD

Haha, alright. it didn't show up when i posted mine.
