### ISSUE TITLE
[Bug] Force Tunes on Weapons do not round correctly

### ISSUE THREAD

**Issue by HC307** [wcqiter/cb-build-simulator#16]
# BUG
Force tunes are not calculated correctly.

# EXAMPLE
Tested on Aquila Girls
3x High Force Tune

At 6 Base Force 

In Cosmic Break rounds out to 8 Force
![image](https://user-images.githubusercontent.com/38377945/116418972-e34e5d80-a83c-11eb-80b9-6b623ac4a425.png)

In Simulater Rounds out to 9 Force
![image](https://user-images.githubusercontent.com/38377945/116419094-024cef80-a83d-11eb-9986-660e80ea2e46.png)

# SUGGESTION
I think % boni on force are all applied first and then it will be rounded. I believe right now you are rounding after every single tune

**Comment by wcqiter** [comment]
Fixed in v1.4.9
