### ISSUE TITLE
Cost25/Capa85 and Cost25/Capa95 / Tune Finalization / Great Force Alpha (+Force,-Ammo)

### ISSUE THREAD

**Issue by reihunter360** [wcqiter/cb-build-simulator#18]
There are some bots with Cost25/Capa85 carts and Cost25/Capa95 carts.

----------------------

Is there a way to see a "finalized" what to tune sheet like...

[Lazflamme BD]
	[Lazflamme LG] [HIGH WLK Beta]
		[Lazflamme BS2] [HIGH WLK Beta]
	[Katana Max BS]
	[Lazflamme AM] [Eternal]
	[Wild Shoulder AMJ] [High TEC Alpha]
		[Lazflamme AM] [High Eternal]
			[Pierce Gun] [Great Force]

From Cosmic Calc ? Even if something like Lazflamme AM becomes AM1 or AM2.

----------------------

Great Force Alpha seems to reduce Range, and not Ammo?

**Comment by wcqiter** [comment]
Fixed in v1.4.9
