### ISSUE TITLE
[Translation] Quick Tune - Missing Translations

### ISSUE THREAD

**Issue by HC307** [wcqiter/cb-build-simulator#19]
# Issue
* The names of the quick tunes are not translated to English in the Quick Tune Menu
* Other, Main and Sub Weapon Tune Category is not translated
![image](https://user-images.githubusercontent.com/38377945/117696290-6c607f80-b1c1-11eb-9fb2-3c306062f6ea.png)

**Comment by wcqiter** [comment]
Fixed!
