### ISSUE TITLE
[Writing] Quick Tuning System Description

### ISSUE THREAD

**Issue by HC307** [wcqiter/cb-build-simulator#20]
# Issue
I've found a few issues with the description of the quick tuning system which I have corrected here. Though English isn't my native language either

# Corrected Description
"Quick Tuning is a feature that allow**s** you to select a tuning first, and then you can directly put this tuning in the slot without the need **for repeated** selecting."

# Suggested Description
Also I have tried to come up with a more concise description. Though I don't really know if this is more helpful or less... so maybe take it with a grain of salt😅

"With the Quick Tuning System you can quickly apply a single Tune Up to multiple slots. Select the Tune Up first and then click on any slot you want the tune up to be in."

P.S.: I hope this doesn't come off  as rude, if it does: i apologize! 😞

**Comment by wcqiter** [comment]
My english is actually bad haha!
Good to have someone to correct me :D

Change the description in latest commit. Thanks!
