### ISSUE TITLE
Capa/Cost Roller + Additional Memory Slots

### ISSUE THREAD

**Issue by reihunter360** [wcqiter/cb-build-simulator#6]
Love the work you're doing.

Can you please turn Capa/Cost into +5/-5 rolls, instead of +1/-1 rolls ?
Its one of the glaring issues i first saw when i started playing around with it.
Its understandable for things like Stats.
Honestly HP could also recieve the same treatment.

As for Additional Memory Slots, some bots actually have 5 of these things. Like cannonballer.

Almost all parts come as 3 Slots, so the slot modifier is kinda excessive imo.
^ nevermind, that's for BD (in case they have any slots)

**Comment by wcqiter** [comment]
In v1.4.3:
- Modified intervals of number input to +/-5
- Added more memory slots
