### ISSUE TITLE
Parts Can Have Both Sub and Main Weapons

### ISSUE THREAD

**Issue by HC307** [wcqiter/cb-build-simulator#8]
In Cosmic Break, Parts can have both main and sub weapons, this is currently not possible. This should be possible.
Also, any part can have a weapon, not just arms

**Comment by wcqiter** [comment]
![image](https://user-images.githubusercontent.com/21999655/115801963-8d2e8400-a410-11eb-80cb-198c838f7b73.png)
Added option to set a part to main / sub weapon (or both) in v1.4.3
