### ISSUE TITLE
Planing Of Weapon Stats

### ISSUE THREAD

**Issue by HC307** [wcqiter/cb-build-simulator#9]
Currently, Weapons in the Simulator are just normal parts.

Actually, weapons have a different set of Stats:

- Force
- Ammo
- Range
- Speed
- Int

**Comment by wcqiter** [comment]
Added weapon stats in v1.4.3
![image](https://user-images.githubusercontent.com/21999655/115801932-7ee06800-a410-11eb-9714-2879560e8464.png)
